CREATE TABLE CHAT_USERS (
	ID INT NOT NULL,
	USERNAME VARCHAR(15) NOT NULL,
	PASSWORD VARCHAR(16) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	TWITTER_USERNAME VARCHAR(15),
	STATUS VARCHAR(10),
	LAST_LOGIN TIMESTAMP,
	CHECK(STATUS = 'online' OR STATUS = 'offline'),
	PRIMARY KEY (ID)
);
	
	
	